spring.application.name=radiotv_pro_escritorio

server.port=8081

# ==========================================
# SQL SERVER - CONFIGURAÇÃO PADRÃO
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=escritorio;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@drS25425643*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==========================================
# POOL DE CONEXÕES (HikariCP)
# ==========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

# ==========================================
# FORMATO DE DATA PARA JSON
# ==========================================
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=America/Sao_Paulo

# ==========================================
# ENVIO DE E-MAIL
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drssistemascontrole@gmail.com
spring.mail.password=icvi kdwp xipl cfze
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
